### ISSUE TITLE
undefined method `[]' for nil:NilClass when caching enabled

### ISSUE THREAD

**Issue by kwent** [jonhue/acts_as_favoritor#15]
**Describe the bug**

First thanks for your OSS contribution !

I'm trying to make it work with cache enabled (cannot repro the bug with cache disabled) (Using upstream version `442e2cd752684f180b712b8abeedaab22ab40e6c`)

When doing 

```ruby
current_user.favorite @product
```

The following exceptions is raised: `undefined method [] for nil:NilClass`.

```
acts_as_favoritor-442e2cd75268/lib/acts_as_favoritor/favoritor.rb:122:in `favorite'
acts_as_favoritor-442e2cd75268/lib/acts_as_favoritor/favoritor_lib.rb:50:in `validate_scopes'
acts_as_favoritor-442e2cd75268/lib/acts_as_favoritor/favoritor.rb:102:in `favorite'
```

This stacktrace is referencing this line: https://github.com/jonhue/acts_as_favoritor/blob/master/lib/acts_as_favoritor/favoritor.rb#L122

Here are my models:

```ruby
class User < ApplicationRecord
  acts_as_favoritor
end
```

```ruby
class Product < ApplicationRecord
  acts_as_favoritable
end
```

Here is my cache migration:

```ruby
class AddFavoritesCacheToUserAndProductTable < ActiveRecord::Migration[5.2]
  def change
    add_column :users, :favoritor_score, :text
    add_column :users, :favoritor_total, :text

    add_column :products, :favoritable_score, :text
    add_column :products, :favoritable_total, :text
  end
end
```

Looks like this `favoritor_score` is never initialized ?

Regards

**Comment by jonhue** [comment]
Should be fixed - please reopen if you're still getting this error.

**Comment by kwent** [comment]
Hi, i have now another error:

`NoMethodError (undefined method `+' for nil:NilClass)`

```ruby
irb(main):040:0> begin
irb(main):041:1> User.first.favorite Product.last
irb(main):042:1> rescue => e
irb(main):043:1> puts e.backtrace
irb(main):044:1> raise e
irb(main):045:1> end
```

```ruby
NoMethodError (undefined method `+' for nil:NilClass)
/Users/username/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/acts_as_favoritor-b84d096e75c6/lib/acts_as_favoritor/favoritor.rb:125:in `favorite'
/Users/username/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/acts_as_favoritor-b84d096e75c6/lib/acts_as_favoritor/favoritor_lib.rb:50:in `validate_scopes'
/Users/username/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/acts_as_favoritor-b84d096e75c6/lib/acts_as_favoritor/favoritor.rb:105:in `favorite'
```

**Comment by jonhue** [comment]
#18
